#See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["dev-kafka-demo/dev-kafka-demo.csproj", "dev-kafka-demo/"]
RUN dotnet restore "dev-kafka-demo/dev-kafka-demo.csproj"
COPY . .
WORKDIR "/src/dev-kafka-demo"
RUN dotnet build "dev-kafka-demo.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "dev-kafka-demo.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "dev-kafka-demo.dll"]